### ISSUE TITLE
@stlkralexdemo, почему коммит называется 'add project'? Вы же в коммите делаете совсем другое?

### ISSUE THREAD

**Issue by coursar** [stlkralexdemo/DepositService#1]
_Originally posted by @coursar in https://github.com/stlkralexdemo/DepositService/commit_comment/create#commitcomment-31338265_

На будущее - внимательно следите за сообщениями о коммитах

**Comment by stlkralexdemo** [comment]
Понял, спасибо. Просто этот проект был давно готов, когда добавлял его в гитхаб начал исправлять ревью и немного запутался, сделал два коммита с одним названием
