### ISSUE TITLE
Расставляйте '_' для удобочитаемости

### ISSUE THREAD

**Issue by coursar** [stlkralexdemo/DepositService#5]
https://github.com/stlkralexdemo/DepositService/blob/4ce5b0302671acf9e223ba94777bedb98a88f99d/src/test/java/ru/itpark/DepositServiceTest.java#L12

Замените на 1_300_000 (на java 11 же работаете).

**Comment by stlkralexdemo** [comment]
Исправил все недочёты, перезалил.
